### PR TITLE
Publish on GH tag

### PR DESCRIPTION
**Pull request by evman182**

### CODE REVIEW

**Comment by bkroeker** [comment]
Can you describe how this works to me?  Do we need to connect github to rubygems's authorized list somehow?  How can we be sure that a tag was a release tag and not some other random tag?

**Comment by evman182** [comment]
@bkroeker The tag would have to start with `v`, but we can tweak it to make it more specific than that. In terms of RubyGems, you'll need to add an API key to the secrets for the repo. I don't think I can do it since you own the repo. Then I'll probably need to tweak the workflow a bit to get it to use the credentials correctly

**Comment by evman182** [comment]
Actually, looks like we can make probably make GHA a trusted published. Will look into it a bit

**Comment by evman182** [comment]
Updated to use the official rubygems publisher action. trusted publisher is setup on rubygems as well

**Review by bkroeker — APPROVED** [review]
Cool, looks good!

**Pull request merged**
